services:
  sketch-follower-ros1:
    container_name: sketch-follower
    image: sketch-follower:ros1
    build:
      context: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/dri:/dev/dri
    tty: true
    entrypoint: ["/bin/bash", "-c", "source devel/setup.bash && roslaunch sketch_follower gazebo.launch"]
