services:
  sketch-follower:
    container_name: sketch-follower
    image: sketch-follower:latest
    build:
      context: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/dri:/dev/dri
    tty: true
    entrypoint: ["/bin/bash", "-c", ". env/bin/activate && source install/setup.bash && ros2 launch sketch_follower rviz_controller.launch.py"]
