joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint_0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: base_arm_slot_joint

joint_1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: arm_link_1_joint

joint_2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: arm_link_2_joint

joint_3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: end_effector_joint
