controller_list:
  - name: fake_Joints_controller
    type: $(arg fake_execution_type)
    joints:
      - link_0_joint
      - link_1_joint
      - sketch_follower_joint
  - name: fake_EndEffector_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: Joints
    pose: Stretched