robot_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  link_0_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_0_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  link_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  link_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}